### ISSUE TITLE
Bezahlungsdaten anzeigen (PF40)

### ISSUE THREAD

**Issue by MoritzM00** [KASTEL-MobilityLab/TES-SS22-VisualizingConfidentialityInMobilitySystems#12]
**Story-Punkte: 4**

## Bezahlungsdaten anzeigen

Als Laie,
möchte ich mir alle Daten zu einer Bezahlung eines Trips im Data Viewer anzeigen lassen können,
um zu wissen, welche Daten erhoben werden und wer Zugriff auf die Daten hat.

## Aufgabenliste

- [ ] Bezahlungsdaten zu einem Trip aus dem Backend anfragen
- [ ] Daten im Data Viewer aktualisieren

**Comment by Danial625** [comment]
Aggregierte Daten #61
